Details/urls.py
from django.urls import path
from . import views
app_name = "Details"
urlpatterns = [
    path('logout/', views.signout, name="Logout"),
    path('skills/', views.skills, name="Skills"),
    path('feed/<int:page>/', views.feed, name="Feed"),
    path('profile/<str:username>', views.profile, name="Profile"),
    path('profile/update/<str:username>/', views.profileupdate, name="ProfileUpdate"),
    path('createTeam/', views.createteam, name="CreateTeam"),
    path('teamprofile/<int:team>/', views.teamprofile, name="TeamProfile"),
    path('teamacceptrequest/<int:team>/<str:user>/', views.teamacceptrequest, name="TeamAcceptRequest"),
    path('teamdeclinerequest/<int:team>/<str:user>/', views.teamdeclinerequest, name="TeamDeclineRequest"),
    path('useracceptrequest/<str:user>/<int:team>', views.useracceptrequest, name="UserAcceptRequest"),
    path('userdeclinerequest/<str:user>/<int:team>', views.userdeclinerequest, name="UserDeclineRequest"),
    path('usersendrequest/<int:team>/<str:user>/', views.usersendrequest, name="UserSendRequest"),
    path('teamsendrequest/<int:team>/',views.teamsendrequest, name="TeamSendRequest"),
    path('teammembersuccess/<int:team>/<str:user>/', views.teammembersuccess, name="TeamMemberSuccess"),
    path('teammemberfailure/<int:team>/<str:user>/', views.teammemberfailure, name="TeamMemberFailure"),
    path('resign/<int:team>/<str:user>/', views.resign, name="Resign"),
    path('feedsearch/<int:page>/', views.search, name="Search"),
]

TalentHunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Registration.urls', namespace='Registration')),
    path('details/',include('Details.urls', namespace='Details')),
]

Details/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Skills(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialization = models.TextField()
    pastexp = models.TextField()
    workexpec = models.TextField()
    bio = models.TextField()
    rating = models.IntegerField(default=0)

class SkillSet(models.Model):
    skills = models.ForeignKey(
        Skills,
        on_delete= models.CASCADE,
        related_name= 'skillset'
    )
    description = models.CharField(max_length=50)
    
class TeamsManager(models.Manager):
    def addMember(self,team,user):
        team.members.create(team=team, user=user)
        team.save()

    def removeMember(self,team,user):
        team.members.filter(team=team, user=user)[0].delete()
        if len(team.members.all()) == 0:
            team.delete()
class Teams(models.Model):
    teamname = models.CharField(max_length = 50)
    def __str__(self):
        return self.teamname
    objects = TeamsManager()

class TeamMembers(models.Model):
    team = models.ForeignKey(
        Teams,
        on_delete= models.CASCADE,
        related_name= "members"
    )
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
        related_name= "users"
    )

class TeamDesc(models.Model):
    team = models.OneToOneField(
        Teams,
        on_delete= models.CASCADE
    )
    teamdescription = models.TextField()
    teammotive = models.TextField()
    
class UserRequests(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='uruser'
    )
    team = models.ForeignKey(
        Teams,
        on_delete=models.CASCADE,
        related_name='urteam'
    )

class TeamRequests(models.Model):
    team = models.ForeignKey(
        Teams,
        on_delete=models.CASCADE,
        related_name='trteam'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='truser'
    )

Details/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from Details.iterator import UserIterator, TeamIterator
from .models import Skills, SkillSet, Teams, TeamDesc, TeamMembers, UserRequests, TeamRequests
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseNotFound
from .datastructure import CardDetails, PageNumber, ProfileDetails, TeamProfile, ProfileTeamList, TeamProfileList, ProfileReqs, TeamReqs, ProfileSendRequest
from django.db.models import Q

# Create your views here.
def signout(request):
    users = User.objects.all()
    teams = Teams.objects.all()

    user_iterator = UserIterator(users)
    team_iterator = TeamIterator(teams)

    for i in user_iterator:
        print(i)

    for i in team_iterator:
        print(i)
        
    logout(request)
    return redirect('Registration:Login')

@login_required
def skills(request):
    if request.method == "POST":
        skill_list = request.POST.getlist('skillset[]')
        valid = True
        if valid:
            skills = Skills(user = request.user, specialization = request.POST['specialization'], pastexp = request.POST['pastexp'], workexpec = request.POST['workexpec'], bio = request.POST['bio'])
            skills.save()
            for i in skill_list:
                obj = skills.skillset.create(description = i)
                obj.save()
            response = {
            'status':0,
            'message':'OK',
            }
            return JsonResponse(response)
    return render(request,'Details/skills.html')

@login_required
def feed(request,page=1):
    if request.method == "GET":
        skilldetails = Skills.objects.all().order_by("-rating")
        start = 10*(page-1)
        end = start + 10
        carddet = []
        for i in range(start, min(len(skilldetails),end)):
            sks = skilldetails[i]
            uobj = User.objects.get(username = sks.user)
            if uobj.username != str(request.user):
                skset = list(sks.skillset.all())
                cd = CardDetails(uobj,sks,skset)
                carddet.append(cd)
        nop = len(skilldetails)//10
        page_number = PageNumber(page)
        context = {'page_number':page_number, 'carddet':carddet, 'np':nop}
        return render(request,'Details/feed.html',context = context)

@login_required
def profile(request,username):
    if str(request.user) == username:
        user = User.objects.get(username = request.user)
        pd = ProfileDetails(user)
        teams = TeamMembers.objects.filter(user=user)
        td = ProfileTeamList(teams)
        reqs = ProfileReqs(user)
        context = {'pd':pd,'td':td,'reqs':reqs,'owner':True}
    else:
        user = User.objects.get(username = username)
        pd = ProfileDetails(user)
        teams = TeamMembers.objects.filter(user=user)
        td = ProfileTeamList(teams)
        reqs = ProfileSendRequest(str(request.user),username)
        context = {'pd':pd, 'td':td,'reqs':reqs,'owner':False}
    return render(request,'Details/profile.html', context=context)

@login_required
def profileupdate(request, username):
    if request.method == "POST":
        user = User.objects.get(username = request.user)
        user.first_name = request.POST['firstname']
        user.last_name = request.POST['lastname']
        user.email = request.POST['email']
        user.extuser.gender = request.POST['gender']
        user.extuser.mobile = request.POST['mobile']
        user.extuser.dob = request.POST['dob']
        li = request.POST.getlist('skillset[]')
        skills = Skills.objects.get(user=user)
        skills.skillset.all().delete()
        for i in li:
            item = SkillSet.objects.create(skills = skills, description=i)
            item.save()
        user.skills.specialization = request.POST['specialization']
        user.skills.pastexp = request.POST['pastexp']
        user.skills.workexpec = request.POST['workexpec']
        user.skills.bio = request.POST['bio']
        user.skills.save()
        user.extuser.save()
        user.save()
        response = {
            'status':0,
            'message':"Profile Updated Successfully!"
        }
        return JsonResponse(response)

@login_required
def createteam(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        teamname = str(request.POST['teamname']).strip()
        teamdescription = str(request.POST['teamdescription']).strip()
        teammotive = str(request.POST['teammotive']).strip()
        if teamname == "":
            error = "Team name cannot be empty!"
            context = {'error':error}
        elif teamdescription == "":
            error = "Team description cannot be empty!"
            context = {'error':error}
        elif teammotive == "":
            error = "Team motive cannot be empty!"
            context = {'error':error}
        else:
            team = Teams.objects.create(teamname = teamname)
            teamdesc = TeamDesc.objects.create(team=team, teamdescription=teamdescription, teammotive=teammotive)
            Teams.objects.addMember(team,user)
            teamdesc.save()
            team.save()
            return redirect('Details:TeamProfile', team=team.pk)
    else:
        context = {}
    return render(request, 'Details/teamcreation.html', context=context)

@login_required
def teamprofile(request, team):
    user = User.objects.get(username = request.user)
    teamitem = Teams.objects.filter(pk=team)
    context={}
    if not teamitem.exists():
        return HttpResponseNotFound('<h3>Page not found</h3>')
    else:
        if request.method == "POST":
            teamdescription = str(request.POST['teamdescription']).strip()
            teammotive = str(request.POST['teammotive']).strip()
            if teamdescription == "":
                error = "Team description cannot be empty!"
                context.update({'message':error})
            elif teammotive == "":
                error = "Team motive cannot be empty!"
                context.update({'message':error})
            else:
                ti = teamitem[0]
                ti.teamdesc.teamdescription = teamdescription
                ti.teamdesc.teammotive = teammotive
                ti.teamdesc.save()
                ti.save()
                context['message']="Updated Successfully!"
        owner = teamitem[0].members.filter(user = user).exists()
        tp = TeamProfile(teamitem[0])
        userlist = TeamMembers.objects.filter(team=teamitem[0])
        mems = TeamProfileList(userlist,str(request.user))
        reqs = TeamReqs(teamitem[0])
        reqsent = TeamRequests.objects.filter(team=teamitem[0], user=user).exists()
        context.update({'tp':tp,'pd':mems,'reqs':reqs,'owner':owner,'reqsent':reqsent})
        return render(request, 'Details/teamprofile.html', context = context)

@login_required
def teamacceptrequest(request,team,user):
    if request.method == "POST":
        t = Teams.objects.get(pk=team)
        u = User.objects.get(username=user)
        tr = TeamRequests.objects.get(team=t, user=u)
        tr.delete()
        Teams.objects.addMember(t,u)
        return redirect('Details:TeamProfile', team=t.pk)

@login_required
def teamdeclinerequest(request,team,user):
    if request.method == "POST":
        t = Teams.objects.get(pk=team)
        u = User.objects.get(username=user)
        tr = TeamRequests.objects.get(team=t, user=u)
        tr.delete()
        return redirect('Details:TeamProfile', team=t.pk)

@login_required
def useracceptrequest(request,user,team):
    if request.method == "POST":
        t = Teams.objects.get(pk=team)
        u = User.objects.get(username=user)
        ur = UserRequests.objects.get(user=u, team=t)
        ur.delete()
        Teams.objects.addMember(t,u)
        return redirect('Details:Profile', username=u.username)

@login_required
def userdeclinerequest(request,user,team):
    if request.method == "POST":
        t = Teams.objects.get(pk=team)
        u = User.objects.get(username=user)
        ur = UserRequests.objects.get(user=u, team=t)
        ur.delete()
        return redirect('Details:Profile', username=u.username)

@login_required
def usersendrequest(request,team,user):
    if request.method == "POST":
        t = Teams.objects.get(pk=team)
        u = User.objects.get(username=user)
        ur = UserRequests.objects.create(user=u, team=t)
        ur.save()
        return redirect('Details:Profile', username=u.username)

@login_required
def teamsendrequest(request,team):
    if request.method == "POST":
        u = User.objects.get(username=str(request.user))
        t = Teams.objects.get(pk=team)
        tr = TeamRequests.objects.create(team=t, user=u)
        tr.save()
        return redirect('Details:TeamProfile', team=t.pk)

@login_required
def teammembersuccess(request,team,user):
    if request.method == "POST":
        u = User.objects.get(username=user)
        t = Teams.objects.get(pk=team)
        Teams.objects.removeMember(t,u)
        u.skills.rating += 10
        u.skills.save()
        return redirect('Details:TeamProfile', team=t.pk)

@login_required
def teammemberfailure(request,team,user):
    if request.method == "POST":
        u = User.objects.get(username=user)
        t = Teams.objects.get(pk=team)
        Teams.objects.removeMember(t,u)
        u.skills.rating -= 10
        return redirect('Details:TeamProfile', team=t.pk)

@login_required
def resign(request,team,user):
    if request.method == "POST":
        u = User.objects.get(username=user)
        t = Teams.objects.get(pk=team)
        Teams.objects.removeMember(t,u)
        return redirect('Details:Profile', username=u.username)

@login_required
def search(request,page=1):
        print(request.GET)
        users = User.objects.filter(Q(first_name__icontains=request.GET["search"])|Q(last_name__icontains=request.GET["search"]))

Details/templates/Details/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'Registration/Images/Logo3.png' %}">
    <style>
        html,body {
                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
                margin:0;
                padding:0;
        }

        #navbar {
            padding: .8rem;
            background: rgba(34, 34, 34, 0.808);
            align-self: center;
        }

        .navbar-nav li {
            padding-right: 20px;
        }

        .nav-btn {
            background: none !important;
            border: none;
        }

        .nav-btn:hover {
            color: rgb(107, 107, 107);
        }

        #nav-search {
            width: 15em;
            height: 1.5em;
        }

        .right {
            align-self: flex-end;
        }
    </style>
    {% block header %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top" >
        <div class = "container-fluid">
            <a class="navbar-brand" href="{% url 'Details:Feed' page=1 %}">
                <img src="{% static 'Registration\Images\Logo3.png' %}" width="50" height="25" alt="Talent Hunt Logo">
                Talent Hunt
            </a>
            <ul class="navbar-nav ml-auto">
                
                <li class="nav-item active" style="padding: 0rem 35rem 0rem 0rem;">
                    <form method="GET" action="{% url 'Details:Search' page=1 %}">
                        <div id="nav-search" class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Search" name="search">
                            <div class="input-group-append">
                                <button class="btn btn-dark" type="submit">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                                        <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
                <li class="nav-item active">
                    <form action="{% url 'Details:Profile' username=request.user %}" method = "POST">
                        {% csrf_token %}
                        <button class="nav-btn" type="submit" style="padding: 0.5rem 1.5rem;">Profile</button>
                    </form>
                </li>
                <li class="nav-item dropdown">
                    <div class="right">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg id="icon" width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                            </svg>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="left: -10rem;">
                            <a class="dropdown-item">
                                {{request.user}}
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'Details:Profile' username=request.user %}">Manage your TH account</a>
                            <a class="dropdown-item" href="{% url 'Details:Logout' %}">Sign out</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    
    {% endblock %}
</body>
</html>

Details/templates/Details/feed.html
{% extends 'Details/base.html' %}
{% load static %}
{% block title %}Talent Hunt | Feed{% endblock %}
{% block header%}
    <style>
        .card {
            width: 100%;
            color: rgb(37, 35, 35);
        }

        .card-header {
            background-color: rgb(99, 99, 99);
            color: whitesmoke;
        }

        .card-body {
            background-color: rgba(211, 211, 211, 0.568);
        }

        .list-group-item,#list-group {
            background-color: rgba(211, 211, 211, 0);
        }

        .page-link {
            border: none;
        }

        #icon {
            color: rgb(46, 46, 46);     
        }

        .jumbotron {
            background-image: url("{% static 'Registration/Images/BackGround5.jpg' %}");
            background-position: right top;
            background-repeat: no-repeat;
            background-size: contain;
            background-color: rgb(32, 32, 32);
            color: rgb(185, 255, 21);
        }

    </style>
{% endblock %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">
                Hello,<br>{{request.user}}
            </h1>
        </div>
    </div>
    {% for item in carddet %}
    <div class="row justify-content-around h-100 row align-items-center">
        <div class="col-sm-6">
            <a class="card-link" href = "{% url 'Details:Profile' username=item.username %}">
                <div class="card">
                    <div class="card-header">
                        <h3>
                            {{ item.fullname }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <ul id="list-group" class="list-group list-group-flush">
                            <li class="list-group-item">
                                <ul>
                                    {% for i in item.skillset %}
                                        <li>{{ i.description }}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li class="list-group-item">{{ item.workexpec }}</li>
                            <li class="list-group-item">
                                <svg id="icon" width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-star-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                </svg>
                                {{ item.rating }}
                            </li>
                        </ul>
                    </div>
                </div>
                <br>
            </a>
        </div>
    </div>
    {% endfor %}
    <div class="row justify-content-around h-100 row align-items-around">
        <ul class="pagination";>
            {% if page_number.previousPage != 0 %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'Details:Feed' page=page_number.previousPage %}">
                        <svg id="icon" width="5em" height="3em" viewBox="0 0 16 16" class="bi bi-caret-left-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                            <path fill-rule="evenodd" d="M10.205 12.456A.5.5 0 0 0 10.5 12V4a.5.5 0 0 0-.832-.374l-4.5 4a.5.5 0 0 0 0 .748l4.5 4a.5.5 0 0 0 .537.082z"/>
                        </svg>
                    </a>
                </li>
            {% endif %}
            {% if page_number.previousPage == 0 %}
                <li class="page-item">
                    <button class="page-link" href="{% url 'Details:Feed' page=page_number.previousPage %}" aria-disabled="true">
                        <svg id="icon" width="5em" height="3em" viewBox="0 0 16 16" class="bi bi-caret-left-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                            <path fill-rule="evenodd" d="M10.205 12.456A.5.5 0 0 0 10.5 12V4a.5.5 0 0 0-.832-.374l-4.5 4a.5.5 0 0 0 0 .748l4.5 4a.5.5 0 0 0 .537.082z"/>
                        </svg>
                    </button>
                </li>
            {% endif %}
            <li class="page-item">
                <a class="page-link" href="{% url 'Details:Feed' page=page_number.nextPage %}">
                    <svg id="icon" width="5em" height="3em" viewBox="0 0 16 16" class="bi bi-caret-right-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                        <path fill-rule="evenodd" d="M5.795 12.456A.5.5 0 0 1 5.5 12V4a.5.5 0 0 1 .832-.374l4.5 4a.5.5 0 0 1 0 .748l-4.5 4a.5.5 0 0 1-.537.082z"/>
                    </svg>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

Details/templates/Details/skills.html
{% extends 'Details/base.html' %}
{% load static %}
{% block title %}Skills Details{% endblock %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'Details/skills.css' %}">
<script type="text/javascript" src="{% static 'Details/skills.js' %}"></script>
<script>
    $(function(){
        $("#sub").click(function(){
            var len = $(".tokenValues").length;
            var arr = [];
            for(var i = 0; i < len; i++){
                arr.push($(".tokenValues").eq(i).text());
            }
            $.ajax({
                type:"POST",
                url:"{% url 'Details:Skills' %}",
                data:{
                    'csrfmiddlewaretoken':"{{csrf_token}}",
                    'skillset': arr,
                    'specialization': $("#specialization").val(),
                    'pastexp': $("#pastexp").val(),
                    'workexpec': $("#workexpec").val(),
                    'bio': $("#bio").val(),
                },
                success: function(response){
                    if (response.status == 0){
                        window.location = "{% url 'Details:Feed' page=1 %}";
                    }
                },
                dataType: 'json'
            });
        });
    });
</script>
{% endblock %}
{% block content %}
<form>
    {% csrf_token %}
    <div class="input-group">
        <input type="text" id="chipValue" class="form-control" placeholder="Add">
        <div class="input-group-btn">
            <button type="button" class="btn btn-outline-primary" id="addToken">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                    <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                </svg>
            </button>
        </div>
    </div>
    <div id="tokens">
    </div>
    <label for="specialization">Specialization</label>
    <textarea id="specialization" name="specialization"></textarea>
    <label for="pastexp">Past Experiences</label>
    <textarea id="pastexp" name="pastexp"></textarea>
    <label for="workexpec">Work Expectations</label>
    <textarea id="workexpec" name="workexpec"></textarea>
    <label for="bio">Bio</label>
    <textarea id="bio" name="bio"></textarea>
    <button type="button" id="sub">Submit</button>
</form>
{% endblock %}

Details/templates/Details/teamcreation.html
{% extends 'Details/base.html' %}
{% load static %}
{% block title %}Team Creation{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<h1>Create Team</h1>
{% if error %}
<h3>{{error}}</h3>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <label for="teamname">Team Name:</label>
    <input type="text" id="teamname" name="teamname" required>
    <label for="teamdescription">Team Description:</label>
    <textarea id="teamdescription" name="teamdescription" required></textarea>
    <label for="teammotive">Team Motive:</label>
    <textarea id="teammotive" name="teammotive" required></textarea>
    <button type="submit">Create</button>
</form>
{% endblock %}